<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <LangVersion>6</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CSharpClassLibrary</RootNamespace>
    <AssemblyName>CSharpClassLibrary</AssemblyName>
    <IsPackable>true</IsPackable>
    <PackageId>CSharpClassLibrary</PackageId>
    <Version>1.0.0</Version>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.3.0" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
